-- Add new column to application_type_schema_entity table
alter table application_type_schema_entity add application_type_assistant_attachments_in_request_supported bit;


-- Add new column to application_type_schema_entity_aud table
alter table application_type_schema_entity_aud add application_type_assistant_attachments_in_request_supported bit;
