# Keycloak
providers.keycloak.issuer=${SECURITY_JWT_ACCEPTED_ISSUERS_KEYCLOAK:}
providers.keycloak.jwk-set-uri=${SECURITY_JWT_JWKS_URI_KEYCLOAK:https:}
providers.keycloak.audiences=${DIAL_ADMIN_CLIENT_ID}, ${SECURITY_JWT_ACCEPTED_AUDIENCES_KEYCLOAK:}
providers.keycloak.role-claims=${SECURITY_ROLES_CLAIM_KEYCLOAK:roles}
# Azure
providers.azure.issuer=${SECURITY_JWT_ACCEPTED_ISSUERS_AZURE:}
providers.azure.jwk-set-uri=${SECURITY_JWT_JWKS_URI_AZURE:https://login.microsoftonline.com/common/discovery/v2.0/keys}
providers.azure.aliases=${SECURITY_JWT_ACCEPTED_ISSUERS_ALIAS_AZURE:}
providers.azure.audiences=${DIAL_ADMIN_CLIENT_ID}, ${SECURITY_JWT_ACCEPTED_AUDIENCES_AZURE:}
providers.azure.role-claims=${SECURITY_ROLES_CLAIM_AZURE:roles}
# Auth0
providers.auth0.issuer=${SECURITY_JWT_ACCEPTED_ISSUERS_AUTH0:}
providers.auth0.jwk-set-uri=${SECURITY_JWT_JWKS_URI_AUTH0:}
providers.auth0.aliases=${SECURITY_JWT_ACCEPTED_ISSUERS_ALIAS_AUTH0:}
providers.auth0.audiences=${DIAL_ADMIN_CLIENT_ID}, ${SECURITY_JWT_ACCEPTED_AUDIENCES_AUTH0:}
providers.auth0.role-claims=${SECURITY_ROLES_CLAIM_AUTH0:roles}
# Okta
providers.okta.issuer=${SECURITY_JWT_ACCEPTED_ISSUERS_OKTA:}
providers.okta.jwk-set-uri=${SECURITY_JWT_JWKS_URI_OKTA:}
providers.okta.aliases=${SECURITY_JWT_ACCEPTED_ISSUERS_ALIAS_OKTA:}
providers.okta.audiences=${DIAL_ADMIN_CLIENT_ID}, ${SECURITY_JWT_ACCEPTED_AUDIENCES_OKTA:}
providers.okta.role-claims=${SECURITY_ROLES_CLAIM_OKTA:roles}
# Cognito
providers.cognito.issuer=${SECURITY_JWT_ACCEPTED_ISSUERS_COGNITO:}
providers.cognito.jwk-set-uri=${SECURITY_JWT_JWKS_URI_COGNITO:}
providers.cognito.aliases=${SECURITY_JWT_ACCEPTED_ISSUERS_ALIAS_COGNITO:}
providers.cognito.audiences=${DIAL_ADMIN_CLIENT_ID}, ${SECURITY_JWT_ACCEPTED_AUDIENCES_COGNITO:}
providers.cognito.role-claims=${SECURITY_ROLES_CLAIM_COGNITO:roles}