spring.application.name=ai-dial-admin-backend

# AIDIAL Config File Exporter
### is export enabled
config.export.enabled=true
### Core config version for export
config.version.target=${CORE_CONFIG_VERSION:latest}
### AI DIAL config export interval in ms
config.export.syncPeriod=15000
config.export.delayConfigReload=${DELAY_CONFIG_RELOAD_MILLISECONDS:5000}
### AI DIAL config destination type. (KUBE_SECRET, CONFIG_MAP, LOCAL_FILE)
config.export.storageType=LOCAL_FILE
## LOCAL_FILE output type props
config.export.outputFile.path=data/export/out.json
## CONFIG_MAP output type props
config.export.configMap.name=
config.export.configMap.key=env.config.json
## KUBE_SECRET output type props
config.export.kubeSecret.name=
config.export.kubeSecret.key=kube-secret-key
## AIDIAL Config Secret Values File Exporter
config.export.keyvault.type=${CONFIG_EXPORT_KEYVAULT_TYPE:none}
config.export.keyvault.secretNames=${CONFIG_EXPORT_KEYVAULT_SECRET_NAMES:}
config.export.keyvault.secretPath=${CONFIG_EXPORT_KEYVAULT_SECRET_PATH:}
config.export.keyvault.expiration.period=${CONFIG_EXPORT_KEYVAULT_EXPIRATION_PERIOD:3}
config.export.keyvault.expiration.unit=${CONFIG_EXPORT_KEYVAULT_EXPIRATION_UNIT:MONTHS}

config.export.createResources=${CONFIG_EXPORT_CREATE_RESOURCES:false}

config.export.exportConfigFileName=aidial.config.json
config.export.exportConfigFileZipName=admin.config.zip
config.export.exportRawConfigFileZipName=admin.raw-config.zip

# kube api connection config
kubernetes-config.connectType=CONFIG_FILE
kubernetes-config.masterUrl=url
kubernetes-config.oauthToken=token
kubernetes-config.trustCerts=false
kubernetes-config.namespace=default
kubernetes-config.client.maxConcurrentRequests=64
kubernetes-config.client.maxConcurrentRequestsPerHost=64
kubernetes-config.client.requestRetryBackoffLimit=10
kubernetes-config.client.requestTimeout=20000
kubernetes-config.client.withWebsocketPingInterval=120000
kubernetes-config.client.withWatchReconnectLimit=16

# Web-Server
server.port=8080

# Security
config.rest.security.mode=${CONFIG_REST_SECURITY_MODE:oidc}
config.rest.security.allowedRoles=${SECURITY_ALLOWED_ROLES:ConfigAdmin,admin}
config.rest.security.principal-claim=${SECURITY_USER_CLAIM:oid}
config.rest.security.roles-claim=${SECURITY_ROLES_CLAIM:roles}
config.rest.security.jwk-key-uris=${SECURITY_JWT_JWKS_URI:https://login.microsoftonline.com/common/discovery/v2.0/keys}
config.rest.security.accepted-issuers=${SECURITY_JWT_ACCEPTED_ISSUERS}
config.rest.security.accepted-issuers-aliases=login.microsoftonline.com, login.windows.net, login.microsoft.com, sts.windows.net, login.partner.microsoftonline.cn, login.chinacloudapi.cn, login.microsoftonline.de, login.microsoftonline.us, login.usgovcloudapi.net, login-us.microsoftonline.com, ${SECURITY_JWT_ACCEPTED_ISSUERS_ALIAS:}
config.rest.security.accepted-audiences=${DIAL_ADMIN_CLIENT_ID}, ${SECURITY_JWT_ACCEPTED_AUDIENCES:}
config.rest.security.disable-swagger-authorization=${DISABLE_SWAGGER_AUTHORIZATION:false}

# azure connection config
azure.auth.type: ${AUTH_AZURE_TYPE:none}
azure.auth.clientId: ${AUTH_AZURE_CLIENT_ID}
azure.auth.tenantId: ${AUTH_AZURE_TENANT_ID}
azure.auth.clientSecret: ${AUTH_AZURE_CLIENT_SECRET}
azure.keyvault.vaultUrl: ${AZURE_KEY_VAULT_URL}

# gcp connection config
gcp.keyvault.projectId: ${GCP_KEY_VAULT_PROJECT_ID}

# DIAL Core
core.client.url=${CORE_CLIENT_URL:localhost:8081}
core.prompts.metadata.default.limit=${CORE_PROMPTS_METADATA_DEFAULT_LIMIT:100}

#Opentelemetry
otel.sdk.disabled=${OTEL_SDK_DISABLED:true}
otel.service.name=dial-admin-backend
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
otel.exporter.otlp.protocol=${OTEL_EXPORTER_OTLP_PROTOCOL}
otel.exporter.otlp.traces.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
otel.exporter.otlp.traces.protocol=${OTEL_EXPORTER_OTLP_PROTOCOL}
otel.exporter.otlp.metrics.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
otel.exporter.otlp.metrics.protocol=${OTEL_EXPORTER_OTLP_PROTOCOL}
otel.exporter.otlp.logs.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
otel.exporter.otlp.logs.protocol=${OTEL_EXPORTER_OTLP_PROTOCOL}
otel.logs.exporter=${OTEL_LOGS_EXPORTER:otlp}
otel.traces.exporter=${OTEL_TRACES_EXPORTER:otlp}
otel.metrics.exporter=${OTEL_METRICS_EXPORTER:otlp}

management.endpoints.web.exposure.include=prometheus,health
management.endpoint.health.show-details=always
management.server.port=9464

# Datastorage
datasource.vendor=${DATASOURCE_VENDOR:H2}
datasource.auth.type=${DATASOURCE_AUTH_TYPE:basic}

h2.datasource.url=jdbc:h2:file:${H2_FILE:./data/testdb};${H2_OPS:CIPHER=AES;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
h2.datasource.driver-class-name=org.h2.Driver
h2.datasource.username=sa
h2.datasource.masterKey=${H2_DATASOURCE_MASTER_KEY}
h2.datasource.encryptedFileKey=${H2_DATASOURCE_ENCRYPTED_FILE_KEY}
h2.datasource.password=${H2_DATASOURCE_PASSWORD}

postgres.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:testdb}?${POSTGRES_OPS:}
postgres.datasource.driver-class-name=org.postgresql.Driver
postgres.datasource.username=${POSTGRES_DATASOURCE_USERNAME:postgres}
postgres.datasource.password=${POSTGRES_DATASOURCE_PASSWORD:postgres}

sqlserver.datasource.url=jdbc:sqlserver://${MS_SQL_SERVER_HOST:localhost}:${MS_SQL_SERVER_PORT:1433};database=${MS_SQL_SERVER_DATABASE:testdb};${MS_SQL_SERVER_OPS:encrypt=true;}
sqlserver.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
sqlserver.datasource.username=${MS_SQL_SERVER_DATASOURCE_USERNAME:sa}
sqlserver.datasource.password=${MS_SQL_SERVER_DATASOURCE_PASSWORD:SQLServerPassword1}

spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/${datasource.vendor}/,classpath:com/epam/aidial/cfg/migration/db
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1.1

# DIAL Rate Analytics metrics config
metrics.enabled=${METRICS_ENABLED:false}
metrics.configFile.contentEnvVar=METRICS_CONFIG_CONTENT
metrics.configFile.location=${METRICS_CONFIG_FILE:data/admin/metric.config.json}

metrics.datasource.influx.defaultPageSize=${METRICS_INFLUX_DEFAULT_PAGE_SIZE:100}

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.epam.aidial.cfg=${APP_LOG_LEVEL:INFO}
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
com.epam.aidial.cfg.configuration.customizable-trace-interceptor.enabled=${CUSTOMIZABLE_TRACE_INTERCEPTOR_ENABLED:true}
com.epam.aidial.cfg.configuration.customizable-trace-interceptor.messages.ENTER=${CUSTOMIZABLE_TRACE_INTERCEPTOR_ENTER_MESSAGE:'Enter: $[methodName](): $[arguments]'}
com.epam.aidial.cfg.configuration.customizable-trace-interceptor.messages.EXIT=${CUSTOMIZABLE_INTERCEPTOR_EXIT_MESSAGE:'Exit: $[methodName]() : in $[invocationTime] ms, returnValue: $[returnValue]'}
com.epam.aidial.cfg.configuration.customizable-trace-interceptor.messages.EXCEPTION=${CUSTOMIZABLE_TRACE_INTERCEPTOR_EXCEPTION_MESSAGE:'Exception: $[methodName]() : in $[invocationTime] ms'}
com.epam.aidial.cfg.configuration.trace-log-advisor.expression=@annotation(com.epam.aidial.cfg.configuration.logging.LogExecution) || @within(com.epam.aidial.cfg.configuration.logging.LogExecution)
server.tomcat.accesslog.pattern="request: method=%m uri=\"%U\" response: statuscode=%s bytes=%b duration=%D(ms) client: remoteip=%a user=%u useragent=\"%{User-Agent}i\""
server.tomcat.accesslog.enabled=${TOMCAT_ACCESSLOG_ENABLED:false}
logger.configuration.path=${LOG_CONFIG_PATH:log-config/logging.levels.json}
logger.configuration.interval=${$LOG_CONFIG_INTERVAL:10}

# s2s retry strategy
feign.retry.period=${FEIGN_RETRY_PERIOD:5000}
feign.retry.maxPeriod=${FEIGN_RETRY_MAX_PERIOD:10000}
feign.retry.maxAttempts=${FEIGN_RETRY_MAX_ATTEMPTS:3}
feign.retry.errorCodes=${FEIGN_RETRY_ERROR_CODES:408,429,500,502,503,504}

prompts.import.consecutiveErrorsThreshold=${PROMPTS_IMPORT_CONSECUTIVE_ERRORS_THRESHOLD:2}
files.import.consecutiveErrorsThreshold=${FILES_IMPORT_CONSECUTIVE_ERRORS_THRESHOLD:2}
config.import.configsMaxCount=${IMPORT_CONFIGS_MAX_COUNT:64}

features.flags.addonsSupported=${ADDONS_SUPPORTED:false}
features.flags.assistantsSupported=${ASSISTANTS_SUPPORTED:false}

# Validation
validation.role.name=${ROLE_NAME_VALIDATION_PATTERN:}
validation.adapter.name=${ADAPTER_NAME_VALIDATION_PATTERN:}
validation.addon.name=${ADDON_NAME_VALIDATION_PATTERN:}
validation.application.name=${APPLICATION_NAME_VALIDATION_PATTERN:}
validation.assistant.name=${ASSISTANT_NAME_VALIDATION_PATTERN:}
validation.interceptor.name=${INTERCEPTOR_NAME_VALIDATION_PATTERN:}
validation.interceptorRunner.name=${INTERCEPTOR_RUNNER_NAME_VALIDATION_PATTERN:}
validation.key.name=${KEY_NAME_VALIDATION_PATTERN:}
validation.model.name=${MODEL_NAME_VALIDATION_PATTERN:}
validation.route.name=${ROUTE_NAME_VALIDATION_PATTERN:}
validation.applicationTypeSchema.id=${APPLICATION_TYPE_SCHEMA_ID_VALIDATION_PATTERN:}