# Keycloak
providers.keycloak.issuer=${SECURITY_JWT_ACCEPTED_ISSUERS_KEYCLOAK:}
providers.keycloak.jwk-set-uri=${SECURITY_JWT_JWKS_URI_KEYCLOAK:https:}
providers.keycloak.audiences=${DIAL_ADMIN_CLIENT_ID}, ${SECURITY_JWT_ACCEPTED_AUDIENCES_KEYCLOAK:}
providers.keycloak.role-claims=${SECURITY_ROLES_CLAIM_KEYCLOAK:roles}
# Azure
providers.azure.issuer=${SECURITY_JWT_ACCEPTED_ISSUERS_AZURE:}
providers.azure.jwk-set-uri=${SECURITY_JWT_JWKS_URI_AZURE:https://login.microsoftonline.com/common/discovery/v2.0/keys}
providers.azure.aliases=${SECURITY_JWT_ACCEPTED_ISSUERS_ALIAS_AZURE:}
providers.azure.audiences=${DIAL_ADMIN_CLIENT_ID}, ${SECURITY_JWT_ACCEPTED_AUDIENCES_AZURE:}
providers.azure.role-claims=${SECURITY_ROLES_CLAIM_AZURE:roles}
