package com.epam.aidial.cfg.domain.model.activity;

public enum ActivityResourceType {
    Adapter,
    Addon,
    Application,
    ApplicationTypeSchema,
    Assistant,
    AssistantsProperty,
    Deployment,
    Interceptor,
    InterceptorRunner,
    Key,
    Model,
    Role,
    RoleLimit,
    Route,
    SecuredResource,
    ToolSet,
    GlobalSettings,
    AdminSettings,
    ImportConfig,
    ExportConfig,
    ToolResource,
    ApplicationResource,
    Prompt,
    File,
    Publication,
    Conversation
}